<?php
global $ritz_pages;
$ritz_pages = array(
"15% discount on Traditional Afternoon Tea",
"15% discount on Traditional Afternoon Tea and The Ritz cookbook",
"A Family Break in London at The Ritz",
"A three-course lunch with a signed Ritz Cookbook",
"Afternoon Tea at The Ritz",
"Afternoon Tea Offers",
"Attractions",
"Banqueting & Events Gallery",
"Beauty is in the eye of the beholder",
"Bed and Breakfast Package",
"Beez@TheRitz",
"Best Rate Guarantee",
"Best Rate Guarantee Terms and Conditions",
"Board-game butler for families over the festive season",
"Body Waxing",
"BOOK A ROOM",
"BOOK A SIGNATURE SUITE",
"BOOK A SUITE",
"Book Accommodation",
"Book in Advance",
"Bookatable Test Page",
"BOXING DAY CELEBRATIONS",
"Boxing Day Dinner",
"Boxing Day Lunch",
"Bridal Services",
"Bridal Treatments",
"Brochures & Factsheets",
"Butler",
"Capacities and Floor Plans",
"Celebration Tea",
"Celebration Tea with Champagne",
"César’s Wine Club Terms and Conditions",
"Champagne Afternoon Tea",
"Charles I: King and Collector at The Royal Academy Afternoon Tea",
"Chauffeur",
"Chelsea Flower Show",
"Christmas activities in London",
"Christmas Afternoon Tea",
"Complimentary upgrade",
"Concierge",
"CONTACT US",
"Create fantastic memories with your family while being in London with these exciting attractions!",
"Creative presents for St Valentine’s Day",
"Deluxe King",
"Deluxe Suites",
"DINE WITH US",
"Dining and Dancing",
"Dining Gallery",
"Dining special offers",
"Dinner with a signed copy of The Ritz Cookbook",
"Dinner, Bed and Breakfast Package",
"EASTER",
"Easter Afternoon Tea",
"Easter Sunday Lunch",
"Event Rooms",
"Events Enquiry",
"Executive King",
"Executive Suites",
"Faberge and The Ritz London create a unique Easter experience",
"Facial Treatments",
"Family Friendly",
"FAQs",
"Festive Dining in The Ritz Restaurant",
"Festive Live at The Ritz",
"FIND AN OFFER",
"Find Us",
"Find your perfect wedding venue",
"Five star luxury with Christmas at The Ritz",
"Friday night live at The Ritz introduces the London Dance Orchestra’s Residency",
"Gallery",
"Gender Pay Gap Report",
"Green Policy",
"Groups at The Ritz",
"Hairdressing & Treatments",
"Hands & Feet Treatments",
"Hiro Miyoshi at The Ritz London",
"Hiro Miyoshi at The Ritz Terms & Conditions",
"Hiro Miyoshi opens at The Ritz London",
"History",
"History Gallery",
"Hotel Gallery",
"How to organise your perfect Christmas party?",
"IMPORTANT INFORMATION",
"Interconnecting Suites",
"Junior Suites",
"Live at The Ritz Restaurant",
"Location",
"Making a difference and the UK with springboard charity",
"Massage Treatments",
"Media Centre",
"Meetings",
"Menus",
"Mother To Be Indulgence Day",
"Mother’s Day Afternoon Tea",
"Mother’s Day at The Ritz London",
"Mother’s Day in The Ritz Restaurant",
"MR SAL GOWILI APPOINTED GENERAL MANAGER OF THE RITZ LONDON",
"Newsletter",
"Our Values",
"Overnight stay and a Fabergé Easter lunch",
"PLAN AN EVENT",
"Pre Theatre Dining",
"Privacy Policy",
"Private Dining",
"Puttin’ on The Ritz",
"Puttin’ on The Ritz Christmas",
"Reassuringly Ritz Package",
"Recent Awards",
"RITZ EVENTS ENQUIRY FORM",
"RITZ GROUP ENQUIRY FORM",
"Ritz Job Search",
"Ritz London Cigars Announcement",
"Ritz Rolls-Royce Phantom",
"RITZ SALON POST STAY FORM",
"Rivoli Bar",
"ROMANCE AT THE RITZ",
"Rooms Gallery",
"Royal Ascot",
"Saturday and Sunday Lunch",
"Save 10% on your city break",
"Seasonal Packages",
"Shopping",
"Simply Sunday",
"Sitemap",
"Special treats for children",
"Stay For Longer",
"Staying safe at The Ritz",
"Suite Indulgence",
"Suite Savings",
"Suites and Room Packages",
"Suites Gallery",
"Superior King",
"Superior Queen",
"Terms & Conditions",
"Thank You",
"The Best Theatre Shows in London",
"THE BURLINGTON ROOM",
"The Grand Hall",
"The Green Park 360 Tour",
"The Green Park Suite",
"THE MARIE ANTOINETTE SUITE",
"The Michelin-starred Ritz Restaurant",
"THE MUSIC ROOM",
"The Piccadilly Suite",
"The Prince of Wales Suite",
"THE QUEEN ELIZABETH ROOM",
"The Restaurant Terrace",
"The Ritz Annual Ball",
"The Ritz Careers Home Page",
"The Ritz Cookbook – Payment Processed",
"The Ritz Cookbook failed",
"The Ritz Cookbook form",
"The Ritz Cookbook form",
"The Ritz Cookbook Signing Event",
"THE RITZ EXPERIENCE",
"The Ritz Garden",
"The Ritz Gift Shop",
"The Ritz London",
"The Ritz London Accessibility",
"The Ritz London achieves a Gold Certificate from Green Tourism",
"The Ritz London adds English Wines to its Livre du Vin",
"The Ritz London and Champagne Barons De Rothschild",
"THE RITZ LONDON EVENTS POST STAY QUESTIONAIRE",
"THE RITZ LONDON MARKS ITS 110TH BIRTHDAY IN 2016 WITH A CALENDAR OF BEST OF BRITISH CELEBRATIONS",
"THE RITZ LONDON NAMED BEST HOTEL IN EUROPE 2017 AT THE ANNUAL ULTRA AWARDS FOR THE SECOND CONSECUTIVE YEAR",
"The Ritz London Policies & Statements",
"The Ritz London Slimline Message",
"THE RITZ LONDON TO REOPEN FOR DINING",
"THE RITZ LONDON UNVEILS NEW GREEN PARK SIGNATURE SUITE",
"THE RITZ LONDON UNVEILS NEW WINE LIST",
"The Ritz London: The Cookbook",
"THE RITZ LONDON’S PARTNERSHIP WITH CLEANCONSCIENCE",
"The Ritz London’s new Rolls-Royce Phantom",
"THE RITZ NAMED BEST HOTEL IN EUROPE 2016 AT THE ANNUAL ULTRA AWARDS",
"The Ritz Relaxation",
"THE RITZ RESTAURANT AWARDED A MICHELIN STAR IN THE MICHELIN GUIDE GREAT BRITAIN AND IRELAND 2017",
"The Ritz Restaurant Menus",
"The Ritz Social Season 2020",
"The Ritz Summer Party",
"The Rivoli Bar Insider – Best cocktail Menu in Mayfair",
"The Rivoli Bar Insider – Churchill’s Courage",
"The Rivoli Bar Insider – Marie Antoinette",
"The Rivoli Bar Launches Its Unique Vintage Cocktail Collection",
"The Royal Suite",
"The Trafalgar Suite",
"The William Kent House Garden",
"The William Kent Room",
"THE WIMBORNE ROOM",
"Theatres",
"Top to Toe",
"Traditional Afternoon Tea",
"Traditional Afternoon Tea and The Ritz cookbook",
"UK winner of “Le Taittinger” International Culinary Prize announced",
"Videos",
"Virtual Tour",
"Waxing & Hair Removal Treatments",
"Wedding Enquiry",
"WEDDING ENQUIRY FORM",
"Wedding Packages",
"Weddings",
"Weddings at The Ritz Gallery",
"Why Stay With Us?",
"Why Work At The Ritz London",
"Your Career",
);

function create_ritz_pages() {
    global $ritz_pages;
    foreach ($ritz_pages as $ritz_page) {
        $check_page_exist = get_page_by_title($ritz_page, 'OBJECT', 'page');
        if(empty($check_page_exist)) {
            $page_id = wp_insert_post(
                array(
                    'comment_status' => 'close',
                    'ping_status'    => 'close',
                    'post_author'    => 1,
                    'post_title'     => ucwords($ritz_page),
                    'post_name'      => strtolower(str_replace(' ', '-', trim($ritz_page))),
                    'post_status'    => 'publish',
                    'post_content'   => '',
                    'post_type'      => 'page',
                )
            );
        }
    }
}

add_action('init','create_ritz_pages');